build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Reine - Product Owner"
    email: "reine@gmail.com"
  onCallSupport:
    - (453) 555-1234
    - (236) 523-1345